/**
 * Cron Schedule Generator for OpenClaw GHL Monitoring
 * Generates `openclaw cron add` commands for automated monitoring checks.
 * Run with --install to auto-register crons on the VPS.
 */

import { execSync } from 'node:child_process';

const SKILL_PATH = '/root/.openclaw/skills/ghl';

const SCHEDULES = [
  {
    name: 'ghl-missed-followups',
    cron: '*/30 * * * *', // Every 30 minutes
    command: `node ${SKILL_PATH}/ghl_monitor.js --check missed_followups`,
    description: 'Check for missed follow-ups every 30 minutes',
  },
  {
    name: 'ghl-stale-leads-morning',
    cron: '0 10 * * 1-5', // 10 AM weekdays
    command: `node ${SKILL_PATH}/ghl_monitor.js --check stale_leads`,
    description: 'Stale lead check at 10 AM weekdays',
  },
  {
    name: 'ghl-stale-leads-afternoon',
    cron: '0 15 * * 1-5', // 3 PM weekdays
    command: `node ${SKILL_PATH}/ghl_monitor.js --check stale_leads`,
    description: 'Stale lead check at 3 PM weekdays',
  },
  {
    name: 'ghl-morning-digest',
    cron: '0 8 * * *', // Daily 8 AM
    command: `node ${SKILL_PATH}/ghl_monitor.js`,
    description: 'Full morning digest — all checks',
  },
  {
    name: 'ghl-weekly-report',
    cron: '0 9 * * 1', // Monday 9 AM
    command: `node ${SKILL_PATH}/ghl_monitor.js --report weekly`,
    description: 'Weekly performance report — Monday 9 AM',
  },
];

function printSchedules() {
  console.log('📅 GHL Monitoring Cron Schedules\n');
  console.log('The following cron jobs will be registered:\n');

  for (const sched of SCHEDULES) {
    console.log(`  ${sched.name}`);
    console.log(`    Schedule: ${sched.cron}`);
    console.log(`    Command:  ${sched.command}`);
    console.log(`    ${sched.description}\n`);
  }

  console.log('Run with --install to register these cron jobs.');
  console.log('Run with --remove to unregister all GHL cron jobs.');
}

function generateCrontab() {
  const lines = ['# GHL MCP Monitoring — Auto-generated by cron_schedule.js'];
  for (const sched of SCHEDULES) {
    lines.push(`# ${sched.description}`);
    lines.push(`${sched.cron} ${sched.command} >> /var/log/ghl-monitor.log 2>&1`);
  }
  return lines.join('\n');
}

function installCrons() {
  console.log('📥 Installing GHL monitoring cron jobs...\n');

  try {
    // Get existing crontab (if any)
    let existing = '';
    try {
      existing = execSync('crontab -l 2>/dev/null', { encoding: 'utf8' });
    } catch { /* no existing crontab */ }

    // Remove any existing GHL entries
    const filtered = existing
      .split('\n')
      .filter(line => !line.includes('ghl_monitor') && !line.includes('GHL MCP'))
      .join('\n')
      .trim();

    // Append new entries
    const newCrontab = filtered + '\n\n' + generateCrontab() + '\n';

    execSync(`echo '${newCrontab.replace(/'/g, "'\\''")}' | crontab -`, { encoding: 'utf8' });

    console.log('✅ Cron jobs installed successfully!\n');
    for (const sched of SCHEDULES) {
      console.log(`  ✅ ${sched.name} — ${sched.cron}`);
    }

    // Create log file
    try {
      execSync('touch /var/log/ghl-monitor.log', { encoding: 'utf8' });
      console.log('\n📝 Log file: /var/log/ghl-monitor.log');
    } catch { /* non-critical */ }
  } catch (err) {
    console.error('❌ Failed to install cron jobs:', err.message);
    process.exit(1);
  }
}

function removeCrons() {
  console.log('🗑️  Removing GHL monitoring cron jobs...\n');

  try {
    let existing = '';
    try {
      existing = execSync('crontab -l 2>/dev/null', { encoding: 'utf8' });
    } catch { /* no existing crontab */ }

    const filtered = existing
      .split('\n')
      .filter(line => !line.includes('ghl_monitor') && !line.includes('GHL MCP'))
      .join('\n')
      .trim();

    if (filtered) {
      execSync(`echo '${filtered.replace(/'/g, "'\\''")}' | crontab -`, { encoding: 'utf8' });
    } else {
      execSync('crontab -r 2>/dev/null', { encoding: 'utf8' });
    }

    console.log('✅ GHL cron jobs removed.');
  } catch (err) {
    console.error('❌ Failed to remove cron jobs:', err.message);
    process.exit(1);
  }
}

// ─── CLI Entry Point ────────────────────────────────────────
const args = process.argv.slice(2);

if (args.includes('--install')) {
  installCrons();
} else if (args.includes('--remove')) {
  removeCrons();
} else if (args.includes('--crontab')) {
  console.log(generateCrontab());
} else {
  printSchedules();
}
